name: linksurf

linksurf: &linksurf
  build: .
  # shared tag so the image is only built once
  image: linksurf
  restart: no
  stop_grace_period: 2m30s
  profiles: [ production ]
  env_file:
    - .env
  depends_on:
    redis:
      condition: service_healthy
    rabbitmq:
      condition: service_healthy
  networks:
    - network

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    profiles: [ development ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
    networks:
      - network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis
    restart: always
    profiles: [ development, production ]
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
    networks:
      - network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    profiles: [ development ]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_consistent_hash_exchange && rabbitmq-server"
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    profiles: [ development, production ]
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  linksurf-1:
    <<: *linksurf
    container_name: linksurf-1
    environment:
      # host overrides when full deployment
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
      IDENTIFIER: 1
      BUCKETS: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16"

  linksurf-2:
    <<: *linksurf
    container_name: linksurf-2
    environment:
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
      IDENTIFIER: 2
      BUCKETS: "17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32"

  linksurf-3:
    <<: *linksurf
    container_name: linksurf-3
    environment:
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
      IDENTIFIER: 3
      BUCKETS: "33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48"

  linksurf-4:
    <<: *linksurf
    container_name: linksurf-4
    environment:
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
      IDENTIFIER: 4
      BUCKETS: "49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64"

volumes:
  mongodb:
  redis:
  minio:
  rabbitmq:

networks:
  network:
    driver: bridge
