name: linksurf

x-linksurf: &linksurf
  build: .
  image: linksurf
  restart: no
  stop_grace_period: 2m30s
  env_file:
    - .env

services:
  linksurf-1:
    <<: *linksurf

  linksurf-2:
    <<: *linksurf

  linksurf-3:
    <<: *linksurf

  linksurf-4:
    <<: *linksurf
